spring:
  security:
    oauth2:
      client:
        provider:
        registration:
          facebook:
            client-id: ${facebook-client-id}
            client-secret: ${facebook-client-secret}
          github:
            client-id: ${github-client-id}
            client-secret: ${github-client-secret}
