---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kidsbank-app
  labels:
    app: kidsbank-app
spec:
  replicas: 1
  template:
    metadata:
      name: kidsbank-app
      labels:
        app: kidsbank-app
      annotations:
        revision: "1"
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: kidsbank-app
          image: itzg/kidsbank-js:0.5.2
          # image: itzg/kidsbank-js:0.6-SNAPSHOT
          #image: itzg/kidsbank-js:0.4.2
          imagePullPolicy: Always
          resources:
            limits:
              memory: 1000Mi
              cpu: 500m
          ports:
            - containerPort: 8080
          env:
             # -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
             #-XX:+FlightRecorder -XX:StartFlightRecording=duration=400s,filename=/tmp/startup.jfr
            - name: JAVA_TOOL_OPTIONS
              value: >
                -XX:MaxRAMPercentage=75
            - name: KIDSBANK_LOGLEVEL
              value: debug
            - name: SPRING_PROFILES_ACTIVE
              value: oauth2
            - name: SERVER_USE_FORWARD_HEADERS
              value: "true"
            - name: SPRING_DATA_MONGODB_HOST
              value: kidsbank-mongo-0.kidsbank-mongo
            - name: FACEBOOK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: client-id
                  name: kidsbank-social-facebook
            - name: FACEBOOK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: client-secret
                  name: kidsbank-social-facebook
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: client-id
                  name: kidsbank-social-github
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: client-secret
                  name: kidsbank-social-github
      restartPolicy: Always
  selector:
    matchLabels:
      app: kidsbank-app
---
apiVersion: v1
kind: Service
metadata:
  name: kidsbank
spec:
  selector:
    app: kidsbank-app
  ports:
    - port: 8080
